### ISSUE TITLE
Not possible to login

### ISSUE THREAD

**Issue by iknowunknown** [Legomaniak/MnfPic#3]
Steps to reproduce:
1. Started MNF console application
2. Added proper user and password into UI window
3. Double clicked on user:

Actual result:
Error message appears
![image](https://user-images.githubusercontent.com/44611364/47725255-e7e02e00-dc60-11e8-82c0-3d38080d29c5.png)

Expected result:
User should be logged in.

**Comment by Legomaniak** [comment]
It seems like u don't have latest version. 
There was a change of Http on Https, it was fixed by commit from  Oct 3, 2018
Thx
Lego

**Comment by iknowunknown** [comment]
Yes I have the latest one. 
I already have https protocol
![image](https://user-images.githubusercontent.com/44611364/47754469-a9b82e00-dca3-11e8-86a3-240fdd5ea400.png)

**Comment by iknowunknown** [comment]
There is some problem with MD5 password calculation. It isn't correct. I hardcoded there mine  that I grab from the browser and everything stared to work,

**Comment by Legomaniak** [comment]
Ok, then use only lower-case letters in your login name :D
