### ISSUE TITLE
theres no link to download

### ISSUE THREAD

**Issue by jzzunl** [Legomaniak/MnfPic#4]
couldnt you post a compiled version to the release tab or say how to compile it in the readme

**Comment by Legomaniak** [comment]
Ok, I will add it soon. Thx

**Comment by sarenstein** [comment]
So hey, sorry beforehand if this is not the place to  ask this, but can I get a link to compiled windows version? 
I've tried to compile and had problems, tried this and that but I'm useless, I don't know the first thing about Visual Studio or even coding.

Thanks.

**Comment by Legomaniak** [comment]
OK, I upload a version [here](https://github.com/Legomaniak/MNF/releases/tag/2.3.26)
Maybe have few bugs :/ but will be new version soon
Lego

**Comment by sarenstein** [comment]
Thank you, my good sir. Much appreciated!
