### ISSUE TITLE
Found Some Warnings

### ISSUE THREAD

**Issue by Question4ble** [Legomaniak/MnfPic#5]
After loading into Visual Studio, I got the following warnings:

The tag 'MnFLogger' does not exist in XML namespace 'clr-namespace:Mnf;assembly=Mnf'. Line 15 Position 10.
The tag 'MnfLogger' does not exist in XML namespace 'clr-namespace:Mnf;assembly=Mnf'. Line 11 Position 10.

When running it through Visual Studio for the first time, it also displays:

CS0162 Unreachable code detected (Project: Mnf File: MnfGame.xaml.cs)
CS0168 The variable 'te' is declared but never used (Project: Mnf File: MnfGame.xaml.cs)

**Comment by Legomaniak** [comment]
A man is smoking a cigarette and blowing smoke rings into the air.  His girlfriend becomes irritated with the smoke and says, “Can’t you see the warning on the cigarette pack?  Smoking is hazardous to your health!” 

To which the man replies, “I am a programmer.  We don’t worry about warnings; we only worry about errors

**Comment by Question4ble** [comment]
This is fair. The main executable still works, just thought I'd report in.

**Comment by Legomaniak** [comment]
XML errors are made by bad reference (or errors in referenced sub project's)
or by mistake in component name.
thx
